[package]
name = "scoped-cell"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[features]
default = ["std", "futures-core"]

futures-core = ["dep:futures-core"]
std = []

[dependencies]
drop-guard.workspace = true
manual-ref.workspace = true

futures-core = { workspace = true, optional = true }

[lints]
workspace = true
