[package]
name = "async-coroutine"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[features]
default = ["alloc", "futures"]

alloc = []
futures = ["dep:futures", "futures-core"]
futures-core = ["dep:futures-core"]
nightly = []

[dependencies]
futures = { workspace = true, optional = true }
futures-core = { workspace = true, optional = true }
pin-project.workspace = true

[lints]
workspace = true
